import type { Metadata } from "next";
import "./globals.css";
import { PresenceManager } from "./components/PresenceManager";

export const metadata: Metadata = {
  title: "Discord Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`antialiased`}>
        <PresenceManager />
        {children}
      </body>
    </html>
  );
}
